name: Python CI

on:
  push:
    branches: [main]  # Trigger action on push to the main branch
  pull_request:
    branches: [main]  # Trigger action on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest

      # Run Black for code formatting checks
      - name: Run Black
        run: black . --check

      # Run unit tests using pytest
      - name: Run Pytest
        run: pytest
